// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: time_data.proto

package com.example.mfind.timetracker;

public final class TimeProto {
  private TimeProto() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TimeDataOrBuilder extends
          // @@protoc_insertion_point(interface_extends:timetracker.TimeData)
          com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    java.util.List<com.example.mfind.timetracker.TimeProto.Day>
    getDayList();
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    com.example.mfind.timetracker.TimeProto.Day getDay(int index);
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    int getDayCount();
  }
  /**
   * Protobuf type {@code timetracker.TimeData}
   */
  public  static final class TimeData extends
          com.google.protobuf.GeneratedMessageLite<
                  TimeData, TimeData.Builder> implements
          // @@protoc_insertion_point(message_implements:timetracker.TimeData)
          TimeDataOrBuilder {
    private TimeData() {
      day_ = emptyProtobufList();
    }
    public static final int DAY_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.example.mfind.timetracker.TimeProto.Day> day_;
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    public java.util.List<com.example.mfind.timetracker.TimeProto.Day> getDayList() {
      return day_;
    }
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    public java.util.List<? extends com.example.mfind.timetracker.TimeProto.DayOrBuilder>
    getDayOrBuilderList() {
      return day_;
    }
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    public int getDayCount() {
      return day_.size();
    }
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    public com.example.mfind.timetracker.TimeProto.Day getDay(int index) {
      return day_.get(index);
    }
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    public com.example.mfind.timetracker.TimeProto.DayOrBuilder getDayOrBuilder(
            int index) {
      return day_.get(index);
    }
    private void ensureDayIsMutable() {
      if (!day_.isModifiable()) {
        day_ =
                com.google.protobuf.GeneratedMessageLite.mutableCopy(day_);
      }
    }

    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    private void setDay(
            int index, com.example.mfind.timetracker.TimeProto.Day value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDayIsMutable();
      day_.set(index, value);
    }
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    private void setDay(
            int index, com.example.mfind.timetracker.TimeProto.Day.Builder builderForValue) {
      ensureDayIsMutable();
      day_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    private void addDay(com.example.mfind.timetracker.TimeProto.Day value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDayIsMutable();
      day_.add(value);
    }
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    private void addDay(
            int index, com.example.mfind.timetracker.TimeProto.Day value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDayIsMutable();
      day_.add(index, value);
    }
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    private void addDay(
            com.example.mfind.timetracker.TimeProto.Day.Builder builderForValue) {
      ensureDayIsMutable();
      day_.add(builderForValue.build());
    }
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    private void addDay(
            int index, com.example.mfind.timetracker.TimeProto.Day.Builder builderForValue) {
      ensureDayIsMutable();
      day_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    private void addAllDay(
            java.lang.Iterable<? extends com.example.mfind.timetracker.TimeProto.Day> values) {
      ensureDayIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
              values, day_);
    }
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    private void clearDay() {
      day_ = emptyProtobufList();
    }
    /**
     * <code>repeated .timetracker.Day day = 1;</code>
     */
    private void removeDay(int index) {
      ensureDayIsMutable();
      day_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      for (int i = 0; i < day_.size(); i++) {
        output.writeMessage(1, day_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < day_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, day_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.example.mfind.timetracker.TimeProto.TimeData parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static com.example.mfind.timetracker.TimeProto.TimeData parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.mfind.timetracker.TimeProto.TimeData parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static com.example.mfind.timetracker.TimeProto.TimeData parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.mfind.timetracker.TimeProto.TimeData parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
    }
    public static com.example.mfind.timetracker.TimeProto.TimeData parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.mfind.timetracker.TimeProto.TimeData parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.mfind.timetracker.TimeProto.TimeData parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.mfind.timetracker.TimeProto.TimeData parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
    }
    public static com.example.mfind.timetracker.TimeProto.TimeData parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.mfind.timetracker.TimeProto.TimeData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code timetracker.TimeData}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    com.example.mfind.timetracker.TimeProto.TimeData, Builder> implements
            // @@protoc_insertion_point(builder_implements:timetracker.TimeData)
            com.example.mfind.timetracker.TimeProto.TimeDataOrBuilder {
      // Construct using com.example.mfind.timetracker.TimeProto.TimeData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .timetracker.Day day = 1;</code>
       */
      public java.util.List<com.example.mfind.timetracker.TimeProto.Day> getDayList() {
        return java.util.Collections.unmodifiableList(
                instance.getDayList());
      }
      /**
       * <code>repeated .timetracker.Day day = 1;</code>
       */
      public int getDayCount() {
        return instance.getDayCount();
      }/**
       * <code>repeated .timetracker.Day day = 1;</code>
       */
      public com.example.mfind.timetracker.TimeProto.Day getDay(int index) {
        return instance.getDay(index);
      }
      /**
       * <code>repeated .timetracker.Day day = 1;</code>
       */
      public Builder setDay(
              int index, com.example.mfind.timetracker.TimeProto.Day value) {
        copyOnWrite();
        instance.setDay(index, value);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day day = 1;</code>
       */
      public Builder setDay(
              int index, com.example.mfind.timetracker.TimeProto.Day.Builder builderForValue) {
        copyOnWrite();
        instance.setDay(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day day = 1;</code>
       */
      public Builder addDay(com.example.mfind.timetracker.TimeProto.Day value) {
        copyOnWrite();
        instance.addDay(value);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day day = 1;</code>
       */
      public Builder addDay(
              int index, com.example.mfind.timetracker.TimeProto.Day value) {
        copyOnWrite();
        instance.addDay(index, value);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day day = 1;</code>
       */
      public Builder addDay(
              com.example.mfind.timetracker.TimeProto.Day.Builder builderForValue) {
        copyOnWrite();
        instance.addDay(builderForValue);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day day = 1;</code>
       */
      public Builder addDay(
              int index, com.example.mfind.timetracker.TimeProto.Day.Builder builderForValue) {
        copyOnWrite();
        instance.addDay(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day day = 1;</code>
       */
      public Builder addAllDay(
              java.lang.Iterable<? extends com.example.mfind.timetracker.TimeProto.Day> values) {
        copyOnWrite();
        instance.addAllDay(values);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day day = 1;</code>
       */
      public Builder clearDay() {
        copyOnWrite();
        instance.clearDay();
        return this;
      }
      /**
       * <code>repeated .timetracker.Day day = 1;</code>
       */
      public Builder removeDay(int index) {
        copyOnWrite();
        instance.removeDay(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:timetracker.TimeData)
    }
    protected final Object dynamicMethod(
            com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
            Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.mfind.timetracker.TimeProto.TimeData();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          day_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.example.mfind.timetracker.TimeProto.TimeData other = (com.example.mfind.timetracker.TimeProto.TimeData) arg1;
          day_= visitor.visitList(day_, other.day_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                  .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
                  (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                  (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!day_.isModifiable()) {
                    day_ =
                            com.google.protobuf.GeneratedMessageLite.mutableCopy(day_);
                  }
                  day_.add(
                          input.readMessage(com.example.mfind.timetracker.TimeProto.Day.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                    new com.google.protobuf.InvalidProtocolBufferException(
                            e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.example.mfind.timetracker.TimeProto.TimeData.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:timetracker.TimeData)
    private static final com.example.mfind.timetracker.TimeProto.TimeData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TimeData();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.example.mfind.timetracker.TimeProto.TimeData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<TimeData> PARSER;

    public static com.google.protobuf.Parser<TimeData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DayOrBuilder extends
          // @@protoc_insertion_point(interface_extends:timetracker.Day)
          com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 year = 1;</code>
     */
    boolean hasYear();
    /**
     * <code>optional int32 year = 1;</code>
     */
    int getYear();

    /**
     * <code>optional int32 month = 2;</code>
     */
    boolean hasMonth();
    /**
     * <code>optional int32 month = 2;</code>
     */
    int getMonth();

    /**
     * <code>optional int32 day = 3;</code>
     */
    boolean hasDay();
    /**
     * <code>optional int32 day = 3;</code>
     */
    int getDay();

    /**
     * <pre>
     * sum of automated measurements
     * </pre>
     *
     * <code>optional int32 ticker_seconds = 4;</code>
     */
    boolean hasTickerSeconds();
    /**
     * <pre>
     * sum of automated measurements
     * </pre>
     *
     * <code>optional int32 ticker_seconds = 4;</code>
     */
    int getTickerSeconds();

    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    java.util.List<com.example.mfind.timetracker.TimeProto.Day.Edit>
    getEditsList();
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    com.example.mfind.timetracker.TimeProto.Day.Edit getEdits(int index);
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    int getEditsCount();
  }
  /**
   * Protobuf type {@code timetracker.Day}
   */
  public  static final class Day extends
          com.google.protobuf.GeneratedMessageLite<
                  Day, Day.Builder> implements
          // @@protoc_insertion_point(message_implements:timetracker.Day)
          DayOrBuilder {
    private Day() {
      edits_ = emptyProtobufList();
    }
    public interface EditOrBuilder extends
            // @@protoc_insertion_point(interface_extends:timetracker.Day.Edit)
            com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <pre>
       * edit local time
       * </pre>
       *
       * <code>optional int32 minute_of_day = 1;</code>
       */
      boolean hasMinuteOfDay();
      /**
       * <pre>
       * edit local time
       * </pre>
       *
       * <code>optional int32 minute_of_day = 1;</code>
       */
      int getMinuteOfDay();

      /**
       * <pre>
       * can be negative
       * </pre>
       *
       * <code>optional int32 delta_minutes = 2;</code>
       */
      boolean hasDeltaMinutes();
      /**
       * <pre>
       * can be negative
       * </pre>
       *
       * <code>optional int32 delta_minutes = 2;</code>
       */
      int getDeltaMinutes();

      /**
       * <code>optional string comment = 3;</code>
       */
      boolean hasComment();
      /**
       * <code>optional string comment = 3;</code>
       */
      java.lang.String getComment();
      /**
       * <code>optional string comment = 3;</code>
       */
      com.google.protobuf.ByteString
      getCommentBytes();
    }
    /**
     * Protobuf type {@code timetracker.Day.Edit}
     */
    public  static final class Edit extends
            com.google.protobuf.GeneratedMessageLite<
                    Edit, Edit.Builder> implements
            // @@protoc_insertion_point(message_implements:timetracker.Day.Edit)
            EditOrBuilder {
      private Edit() {
        comment_ = "";
      }
      private int bitField0_;
      public static final int MINUTE_OF_DAY_FIELD_NUMBER = 1;
      private int minuteOfDay_;
      /**
       * <pre>
       * edit local time
       * </pre>
       *
       * <code>optional int32 minute_of_day = 1;</code>
       */
      public boolean hasMinuteOfDay() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * edit local time
       * </pre>
       *
       * <code>optional int32 minute_of_day = 1;</code>
       */
      public int getMinuteOfDay() {
        return minuteOfDay_;
      }
      /**
       * <pre>
       * edit local time
       * </pre>
       *
       * <code>optional int32 minute_of_day = 1;</code>
       */
      private void setMinuteOfDay(int value) {
        bitField0_ |= 0x00000001;
        minuteOfDay_ = value;
      }
      /**
       * <pre>
       * edit local time
       * </pre>
       *
       * <code>optional int32 minute_of_day = 1;</code>
       */
      private void clearMinuteOfDay() {
        bitField0_ = (bitField0_ & ~0x00000001);
        minuteOfDay_ = 0;
      }

      public static final int DELTA_MINUTES_FIELD_NUMBER = 2;
      private int deltaMinutes_;
      /**
       * <pre>
       * can be negative
       * </pre>
       *
       * <code>optional int32 delta_minutes = 2;</code>
       */
      public boolean hasDeltaMinutes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * can be negative
       * </pre>
       *
       * <code>optional int32 delta_minutes = 2;</code>
       */
      public int getDeltaMinutes() {
        return deltaMinutes_;
      }
      /**
       * <pre>
       * can be negative
       * </pre>
       *
       * <code>optional int32 delta_minutes = 2;</code>
       */
      private void setDeltaMinutes(int value) {
        bitField0_ |= 0x00000002;
        deltaMinutes_ = value;
      }
      /**
       * <pre>
       * can be negative
       * </pre>
       *
       * <code>optional int32 delta_minutes = 2;</code>
       */
      private void clearDeltaMinutes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deltaMinutes_ = 0;
      }

      public static final int COMMENT_FIELD_NUMBER = 3;
      private java.lang.String comment_;
      /**
       * <code>optional string comment = 3;</code>
       */
      public boolean hasComment() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string comment = 3;</code>
       */
      public java.lang.String getComment() {
        return comment_;
      }
      /**
       * <code>optional string comment = 3;</code>
       */
      public com.google.protobuf.ByteString
      getCommentBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(comment_);
      }
      /**
       * <code>optional string comment = 3;</code>
       */
      private void setComment(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        comment_ = value;
      }
      /**
       * <code>optional string comment = 3;</code>
       */
      private void clearComment() {
        bitField0_ = (bitField0_ & ~0x00000004);
        comment_ = getDefaultInstance().getComment();
      }
      /**
       * <code>optional string comment = 3;</code>
       */
      private void setCommentBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        comment_ = value.toStringUtf8();
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
              throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, minuteOfDay_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, deltaMinutes_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeString(3, getComment());
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
                  .computeInt32Size(1, minuteOfDay_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
                  .computeInt32Size(2, deltaMinutes_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
                  .computeStringSize(3, getComment());
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      public static com.example.mfind.timetracker.TimeProto.Day.Edit parseFrom(
              com.google.protobuf.ByteString data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
      }
      public static com.example.mfind.timetracker.TimeProto.Day.Edit parseFrom(
              com.google.protobuf.ByteString data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.example.mfind.timetracker.TimeProto.Day.Edit parseFrom(byte[] data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
      }
      public static com.example.mfind.timetracker.TimeProto.Day.Edit parseFrom(
              byte[] data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.example.mfind.timetracker.TimeProto.Day.Edit parseFrom(java.io.InputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
      }
      public static com.example.mfind.timetracker.TimeProto.Day.Edit parseFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.example.mfind.timetracker.TimeProto.Day.Edit parseDelimitedFrom(java.io.InputStream input)
              throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static com.example.mfind.timetracker.TimeProto.Day.Edit parseDelimitedFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.example.mfind.timetracker.TimeProto.Day.Edit parseFrom(
              com.google.protobuf.CodedInputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
      }
      public static com.example.mfind.timetracker.TimeProto.Day.Edit parseFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.example.mfind.timetracker.TimeProto.Day.Edit prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code timetracker.Day.Edit}
       */
      public static final class Builder extends
              com.google.protobuf.GeneratedMessageLite.Builder<
                      com.example.mfind.timetracker.TimeProto.Day.Edit, Builder> implements
              // @@protoc_insertion_point(builder_implements:timetracker.Day.Edit)
              com.example.mfind.timetracker.TimeProto.Day.EditOrBuilder {
        // Construct using com.example.mfind.timetracker.TimeProto.Day.Edit.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <pre>
         * edit local time
         * </pre>
         *
         * <code>optional int32 minute_of_day = 1;</code>
         */
        public boolean hasMinuteOfDay() {
          return instance.hasMinuteOfDay();
        }
        /**
         * <pre>
         * edit local time
         * </pre>
         *
         * <code>optional int32 minute_of_day = 1;</code>
         */
        public int getMinuteOfDay() {
          return instance.getMinuteOfDay();
        }
        /**
         * <pre>
         * edit local time
         * </pre>
         *
         * <code>optional int32 minute_of_day = 1;</code>
         */
        public Builder setMinuteOfDay(int value) {
          copyOnWrite();
          instance.setMinuteOfDay(value);
          return this;
        }
        /**
         * <pre>
         * edit local time
         * </pre>
         *
         * <code>optional int32 minute_of_day = 1;</code>
         */
        public Builder clearMinuteOfDay() {
          copyOnWrite();
          instance.clearMinuteOfDay();
          return this;
        }

        /**
         * <pre>
         * can be negative
         * </pre>
         *
         * <code>optional int32 delta_minutes = 2;</code>
         */
        public boolean hasDeltaMinutes() {
          return instance.hasDeltaMinutes();
        }
        /**
         * <pre>
         * can be negative
         * </pre>
         *
         * <code>optional int32 delta_minutes = 2;</code>
         */
        public int getDeltaMinutes() {
          return instance.getDeltaMinutes();
        }
        /**
         * <pre>
         * can be negative
         * </pre>
         *
         * <code>optional int32 delta_minutes = 2;</code>
         */
        public Builder setDeltaMinutes(int value) {
          copyOnWrite();
          instance.setDeltaMinutes(value);
          return this;
        }
        /**
         * <pre>
         * can be negative
         * </pre>
         *
         * <code>optional int32 delta_minutes = 2;</code>
         */
        public Builder clearDeltaMinutes() {
          copyOnWrite();
          instance.clearDeltaMinutes();
          return this;
        }

        /**
         * <code>optional string comment = 3;</code>
         */
        public boolean hasComment() {
          return instance.hasComment();
        }
        /**
         * <code>optional string comment = 3;</code>
         */
        public java.lang.String getComment() {
          return instance.getComment();
        }
        /**
         * <code>optional string comment = 3;</code>
         */
        public com.google.protobuf.ByteString
        getCommentBytes() {
          return instance.getCommentBytes();
        }
        /**
         * <code>optional string comment = 3;</code>
         */
        public Builder setComment(
                java.lang.String value) {
          copyOnWrite();
          instance.setComment(value);
          return this;
        }
        /**
         * <code>optional string comment = 3;</code>
         */
        public Builder clearComment() {
          copyOnWrite();
          instance.clearComment();
          return this;
        }
        /**
         * <code>optional string comment = 3;</code>
         */
        public Builder setCommentBytes(
                com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setCommentBytes(value);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:timetracker.Day.Edit)
      }
      protected final Object dynamicMethod(
              com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
              Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new com.example.mfind.timetracker.TimeProto.Day.Edit();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            com.example.mfind.timetracker.TimeProto.Day.Edit other = (com.example.mfind.timetracker.TimeProto.Day.Edit) arg1;
            minuteOfDay_ = visitor.visitInt(
                    hasMinuteOfDay(), minuteOfDay_,
                    other.hasMinuteOfDay(), other.minuteOfDay_);
            deltaMinutes_ = visitor.visitInt(
                    hasDeltaMinutes(), deltaMinutes_,
                    other.hasDeltaMinutes(), other.deltaMinutes_);
            comment_ = visitor.visitString(
                    hasComment(), comment_,
                    other.hasComment(), other.comment_);
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                    .INSTANCE) {
              bitField0_ |= other.bitField0_;
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                    (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                    (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!parseUnknownField(tag, input)) {
                      done = true;
                    }
                    break;
                  }
                  case 8: {
                    bitField0_ |= 0x00000001;
                    minuteOfDay_ = input.readInt32();
                    break;
                  }
                  case 16: {
                    bitField0_ |= 0x00000002;
                    deltaMinutes_ = input.readInt32();
                    break;
                  }
                  case 26: {
                    String s = input.readString();
                    bitField0_ |= 0x00000004;
                    comment_ = s;
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                      new com.google.protobuf.InvalidProtocolBufferException(
                              e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (com.example.mfind.timetracker.TimeProto.Day.Edit.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:timetracker.Day.Edit)
      private static final com.example.mfind.timetracker.TimeProto.Day.Edit DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Edit();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static com.example.mfind.timetracker.TimeProto.Day.Edit getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Edit> PARSER;

      public static com.google.protobuf.Parser<Edit> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int YEAR_FIELD_NUMBER = 1;
    private int year_;
    /**
     * <code>optional int32 year = 1;</code>
     */
    public boolean hasYear() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 year = 1;</code>
     */
    public int getYear() {
      return year_;
    }
    /**
     * <code>optional int32 year = 1;</code>
     */
    private void setYear(int value) {
      bitField0_ |= 0x00000001;
      year_ = value;
    }
    /**
     * <code>optional int32 year = 1;</code>
     */
    private void clearYear() {
      bitField0_ = (bitField0_ & ~0x00000001);
      year_ = 0;
    }

    public static final int MONTH_FIELD_NUMBER = 2;
    private int month_;
    /**
     * <code>optional int32 month = 2;</code>
     */
    public boolean hasMonth() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 month = 2;</code>
     */
    public int getMonth() {
      return month_;
    }
    /**
     * <code>optional int32 month = 2;</code>
     */
    private void setMonth(int value) {
      bitField0_ |= 0x00000002;
      month_ = value;
    }
    /**
     * <code>optional int32 month = 2;</code>
     */
    private void clearMonth() {
      bitField0_ = (bitField0_ & ~0x00000002);
      month_ = 0;
    }

    public static final int DAY_FIELD_NUMBER = 3;
    private int day_;
    /**
     * <code>optional int32 day = 3;</code>
     */
    public boolean hasDay() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 day = 3;</code>
     */
    public int getDay() {
      return day_;
    }
    /**
     * <code>optional int32 day = 3;</code>
     */
    private void setDay(int value) {
      bitField0_ |= 0x00000004;
      day_ = value;
    }
    /**
     * <code>optional int32 day = 3;</code>
     */
    private void clearDay() {
      bitField0_ = (bitField0_ & ~0x00000004);
      day_ = 0;
    }

    public static final int TICKER_SECONDS_FIELD_NUMBER = 4;
    private int tickerSeconds_;
    /**
     * <pre>
     * sum of automated measurements
     * </pre>
     *
     * <code>optional int32 ticker_seconds = 4;</code>
     */
    public boolean hasTickerSeconds() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * sum of automated measurements
     * </pre>
     *
     * <code>optional int32 ticker_seconds = 4;</code>
     */
    public int getTickerSeconds() {
      return tickerSeconds_;
    }
    /**
     * <pre>
     * sum of automated measurements
     * </pre>
     *
     * <code>optional int32 ticker_seconds = 4;</code>
     */
    private void setTickerSeconds(int value) {
      bitField0_ |= 0x00000008;
      tickerSeconds_ = value;
    }
    /**
     * <pre>
     * sum of automated measurements
     * </pre>
     *
     * <code>optional int32 ticker_seconds = 4;</code>
     */
    private void clearTickerSeconds() {
      bitField0_ = (bitField0_ & ~0x00000008);
      tickerSeconds_ = 0;
    }

    public static final int EDITS_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.ProtobufList<com.example.mfind.timetracker.TimeProto.Day.Edit> edits_;
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    public java.util.List<com.example.mfind.timetracker.TimeProto.Day.Edit> getEditsList() {
      return edits_;
    }
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    public java.util.List<? extends com.example.mfind.timetracker.TimeProto.Day.EditOrBuilder>
    getEditsOrBuilderList() {
      return edits_;
    }
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    public int getEditsCount() {
      return edits_.size();
    }
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    public com.example.mfind.timetracker.TimeProto.Day.Edit getEdits(int index) {
      return edits_.get(index);
    }
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    public com.example.mfind.timetracker.TimeProto.Day.EditOrBuilder getEditsOrBuilder(
            int index) {
      return edits_.get(index);
    }
    private void ensureEditsIsMutable() {
      if (!edits_.isModifiable()) {
        edits_ =
                com.google.protobuf.GeneratedMessageLite.mutableCopy(edits_);
      }
    }

    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    private void setEdits(
            int index, com.example.mfind.timetracker.TimeProto.Day.Edit value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureEditsIsMutable();
      edits_.set(index, value);
    }
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    private void setEdits(
            int index, com.example.mfind.timetracker.TimeProto.Day.Edit.Builder builderForValue) {
      ensureEditsIsMutable();
      edits_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    private void addEdits(com.example.mfind.timetracker.TimeProto.Day.Edit value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureEditsIsMutable();
      edits_.add(value);
    }
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    private void addEdits(
            int index, com.example.mfind.timetracker.TimeProto.Day.Edit value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureEditsIsMutable();
      edits_.add(index, value);
    }
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    private void addEdits(
            com.example.mfind.timetracker.TimeProto.Day.Edit.Builder builderForValue) {
      ensureEditsIsMutable();
      edits_.add(builderForValue.build());
    }
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    private void addEdits(
            int index, com.example.mfind.timetracker.TimeProto.Day.Edit.Builder builderForValue) {
      ensureEditsIsMutable();
      edits_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    private void addAllEdits(
            java.lang.Iterable<? extends com.example.mfind.timetracker.TimeProto.Day.Edit> values) {
      ensureEditsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
              values, edits_);
    }
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    private void clearEdits() {
      edits_ = emptyProtobufList();
    }
    /**
     * <code>repeated .timetracker.Day.Edit edits = 5;</code>
     */
    private void removeEdits(int index) {
      ensureEditsIsMutable();
      edits_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, year_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, month_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, day_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, tickerSeconds_);
      }
      for (int i = 0; i < edits_.size(); i++) {
        output.writeMessage(5, edits_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, year_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(2, month_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(3, day_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(4, tickerSeconds_);
      }
      for (int i = 0; i < edits_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(5, edits_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.example.mfind.timetracker.TimeProto.Day parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static com.example.mfind.timetracker.TimeProto.Day parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.mfind.timetracker.TimeProto.Day parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static com.example.mfind.timetracker.TimeProto.Day parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.mfind.timetracker.TimeProto.Day parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
    }
    public static com.example.mfind.timetracker.TimeProto.Day parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.mfind.timetracker.TimeProto.Day parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.mfind.timetracker.TimeProto.Day parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.mfind.timetracker.TimeProto.Day parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
    }
    public static com.example.mfind.timetracker.TimeProto.Day parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.mfind.timetracker.TimeProto.Day prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code timetracker.Day}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    com.example.mfind.timetracker.TimeProto.Day, Builder> implements
            // @@protoc_insertion_point(builder_implements:timetracker.Day)
            com.example.mfind.timetracker.TimeProto.DayOrBuilder {
      // Construct using com.example.mfind.timetracker.TimeProto.Day.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 year = 1;</code>
       */
      public boolean hasYear() {
        return instance.hasYear();
      }
      /**
       * <code>optional int32 year = 1;</code>
       */
      public int getYear() {
        return instance.getYear();
      }
      /**
       * <code>optional int32 year = 1;</code>
       */
      public Builder setYear(int value) {
        copyOnWrite();
        instance.setYear(value);
        return this;
      }
      /**
       * <code>optional int32 year = 1;</code>
       */
      public Builder clearYear() {
        copyOnWrite();
        instance.clearYear();
        return this;
      }

      /**
       * <code>optional int32 month = 2;</code>
       */
      public boolean hasMonth() {
        return instance.hasMonth();
      }
      /**
       * <code>optional int32 month = 2;</code>
       */
      public int getMonth() {
        return instance.getMonth();
      }
      /**
       * <code>optional int32 month = 2;</code>
       */
      public Builder setMonth(int value) {
        copyOnWrite();
        instance.setMonth(value);
        return this;
      }
      /**
       * <code>optional int32 month = 2;</code>
       */
      public Builder clearMonth() {
        copyOnWrite();
        instance.clearMonth();
        return this;
      }

      /**
       * <code>optional int32 day = 3;</code>
       */
      public boolean hasDay() {
        return instance.hasDay();
      }
      /**
       * <code>optional int32 day = 3;</code>
       */
      public int getDay() {
        return instance.getDay();
      }
      /**
       * <code>optional int32 day = 3;</code>
       */
      public Builder setDay(int value) {
        copyOnWrite();
        instance.setDay(value);
        return this;
      }
      /**
       * <code>optional int32 day = 3;</code>
       */
      public Builder clearDay() {
        copyOnWrite();
        instance.clearDay();
        return this;
      }

      /**
       * <pre>
       * sum of automated measurements
       * </pre>
       *
       * <code>optional int32 ticker_seconds = 4;</code>
       */
      public boolean hasTickerSeconds() {
        return instance.hasTickerSeconds();
      }
      /**
       * <pre>
       * sum of automated measurements
       * </pre>
       *
       * <code>optional int32 ticker_seconds = 4;</code>
       */
      public int getTickerSeconds() {
        return instance.getTickerSeconds();
      }
      /**
       * <pre>
       * sum of automated measurements
       * </pre>
       *
       * <code>optional int32 ticker_seconds = 4;</code>
       */
      public Builder setTickerSeconds(int value) {
        copyOnWrite();
        instance.setTickerSeconds(value);
        return this;
      }
      /**
       * <pre>
       * sum of automated measurements
       * </pre>
       *
       * <code>optional int32 ticker_seconds = 4;</code>
       */
      public Builder clearTickerSeconds() {
        copyOnWrite();
        instance.clearTickerSeconds();
        return this;
      }

      /**
       * <code>repeated .timetracker.Day.Edit edits = 5;</code>
       */
      public java.util.List<com.example.mfind.timetracker.TimeProto.Day.Edit> getEditsList() {
        return java.util.Collections.unmodifiableList(
                instance.getEditsList());
      }
      /**
       * <code>repeated .timetracker.Day.Edit edits = 5;</code>
       */
      public int getEditsCount() {
        return instance.getEditsCount();
      }/**
       * <code>repeated .timetracker.Day.Edit edits = 5;</code>
       */
      public com.example.mfind.timetracker.TimeProto.Day.Edit getEdits(int index) {
        return instance.getEdits(index);
      }
      /**
       * <code>repeated .timetracker.Day.Edit edits = 5;</code>
       */
      public Builder setEdits(
              int index, com.example.mfind.timetracker.TimeProto.Day.Edit value) {
        copyOnWrite();
        instance.setEdits(index, value);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day.Edit edits = 5;</code>
       */
      public Builder setEdits(
              int index, com.example.mfind.timetracker.TimeProto.Day.Edit.Builder builderForValue) {
        copyOnWrite();
        instance.setEdits(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day.Edit edits = 5;</code>
       */
      public Builder addEdits(com.example.mfind.timetracker.TimeProto.Day.Edit value) {
        copyOnWrite();
        instance.addEdits(value);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day.Edit edits = 5;</code>
       */
      public Builder addEdits(
              int index, com.example.mfind.timetracker.TimeProto.Day.Edit value) {
        copyOnWrite();
        instance.addEdits(index, value);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day.Edit edits = 5;</code>
       */
      public Builder addEdits(
              com.example.mfind.timetracker.TimeProto.Day.Edit.Builder builderForValue) {
        copyOnWrite();
        instance.addEdits(builderForValue);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day.Edit edits = 5;</code>
       */
      public Builder addEdits(
              int index, com.example.mfind.timetracker.TimeProto.Day.Edit.Builder builderForValue) {
        copyOnWrite();
        instance.addEdits(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day.Edit edits = 5;</code>
       */
      public Builder addAllEdits(
              java.lang.Iterable<? extends com.example.mfind.timetracker.TimeProto.Day.Edit> values) {
        copyOnWrite();
        instance.addAllEdits(values);
        return this;
      }
      /**
       * <code>repeated .timetracker.Day.Edit edits = 5;</code>
       */
      public Builder clearEdits() {
        copyOnWrite();
        instance.clearEdits();
        return this;
      }
      /**
       * <code>repeated .timetracker.Day.Edit edits = 5;</code>
       */
      public Builder removeEdits(int index) {
        copyOnWrite();
        instance.removeEdits(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:timetracker.Day)
    }
    protected final Object dynamicMethod(
            com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
            Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.mfind.timetracker.TimeProto.Day();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          edits_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.example.mfind.timetracker.TimeProto.Day other = (com.example.mfind.timetracker.TimeProto.Day) arg1;
          year_ = visitor.visitInt(
                  hasYear(), year_,
                  other.hasYear(), other.year_);
          month_ = visitor.visitInt(
                  hasMonth(), month_,
                  other.hasMonth(), other.month_);
          day_ = visitor.visitInt(
                  hasDay(), day_,
                  other.hasDay(), other.day_);
          tickerSeconds_ = visitor.visitInt(
                  hasTickerSeconds(), tickerSeconds_,
                  other.hasTickerSeconds(), other.tickerSeconds_);
          edits_= visitor.visitList(edits_, other.edits_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                  .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
                  (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                  (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  year_ = input.readInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  month_ = input.readInt32();
                  break;
                }
                case 24: {
                  bitField0_ |= 0x00000004;
                  day_ = input.readInt32();
                  break;
                }
                case 32: {
                  bitField0_ |= 0x00000008;
                  tickerSeconds_ = input.readInt32();
                  break;
                }
                case 42: {
                  if (!edits_.isModifiable()) {
                    edits_ =
                            com.google.protobuf.GeneratedMessageLite.mutableCopy(edits_);
                  }
                  edits_.add(
                          input.readMessage(com.example.mfind.timetracker.TimeProto.Day.Edit.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                    new com.google.protobuf.InvalidProtocolBufferException(
                            e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.example.mfind.timetracker.TimeProto.Day.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:timetracker.Day)
    private static final com.example.mfind.timetracker.TimeProto.Day DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Day();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.example.mfind.timetracker.TimeProto.Day getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Day> PARSER;

    public static com.google.protobuf.Parser<Day> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
